name: mi_card_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - images/
  fonts:
    - family: SouceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf
    - family: EuphoriaScript
      fonts:
        - asset: fonts/EuphoriaScript-Regular.ttf
    - family: PTSans
      fonts:
        - asset: fonts/PTSans-Regular.ttf
    - family: PTSerif
      fonts:
        - asset: fonts/PTSerif-Regular.ttf





  module:
    androidX: true
    androidPackage: com.example.mi_card_flutter
    iosBundleIdentifier: com.example.miCardFlutter
